[package]
name = "rust_os"
version = "0.1.0"
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
# cortex-m = "0.7.3"
# cortex-m-rt = "0.7.1"
# panic-halt = "0.2.0"

[build-dependencies]
# cc = "1.0"
