[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-rust_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[target.x86_64-rust_os]
rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "target-cpu=x86-64",
]