[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
# target = "thumbv7em-none-eabihf"
target = "x86_64-rust_os.json"

# [target.x86_64-rust_os]
# linker = "rust-lld"
# rustflags = [
#     "-C", "link-arg=-nostartfiles",
#     "-C", "link-arg=-Tlink.x",
# ]

# [target.thumbv7em-none-eabihf]
# rustflags = [
#     "-C", "link-arg=-nostartfiles",
#     "-C", "link-arg=-Tlink.x",
# ]


[target.'cfg(target_os = "none")']
runner = "bootimage runner"